id: p1
name: pipeline1
description: ""
version: "1.0"
enabled: true
properties: {}
trigger:
    type: opcua
    function: opcua_read
    config:
        node_id: ns=3;i=1001
        timeout: 5000
nodes:
    - id: state_machine_7kazg
      name: state_machine
      type: transform
      function: state_machine
      config:
        machine_id: machine1
      depends_on:
        - trigger
    - id: add_to_dashboard_alhju
      name: add_to_dashboard
      type: output
      function: add_to_dashboard
      config:
        kind: value
        label: Mon widget
      depends_on:
        - state_machine_7kazg
output: add_to_dashboard_alhju
